---
- name: Yum install chrony
  ansible.builtin.package:
    name: chrony
  notify: Restart chronyd (RedHat)

- name: Service start chronyd
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
