---

- hosts: compute
  become: true
  tasks:
    - name: Disable SELinux
      selinux:
        state: permissive
        policy: targeted

- hosts: compute
  become: true
  roles:
    - citc_user
    - filesystem
    - ssh
    - ntp
    - sssd
    - lmod
    - packages
    - mpi
    - slurm
    - monitoring
