---

- name: Enable 389-ds module
  ansible.builtin.command:
    cmd: dnf module enable -y 389-ds:1.4
  register: dnf_result
  changed_when: '"Nothing to do" not in dnf_result.stdout'

- name: Install 389-ds
  ansible.builtin.package:
    name: 389-ds-base

- name: Check if 389 setup already run
  ansible.builtin.command: systemctl list-unit-files dirsrv@.service  # noqa no-changed-when command-instead-of-module
  register: dirsrv_unit_list

- name: Copy 389 config template
  ansible.builtin.template:
    src: ds389.inf.j2
    dest: /root/389ds.inf
    mode: u=rw,g=r,o=
  when: "'disabled' in dirsrv_unit_list.stdout"

- name: Run dscreate
  ansible.builtin.command: dscreate from-file /root/389ds.inf
  changed_when: true
  when: "'disabled' in dirsrv_unit_list.stdout"

- name: Start dirsrv
  ansible.builtin.service:
    name: "dirsrv@{{ mgmt_hostname }}"
    state: started

- name: Setup TLS for LDAP
  ansible.builtin.include_tasks: tls.yml

- name: Wait for LDAP server to be ready
  ansible.builtin.wait_for:
    host: "{{ mgmt_hostname }}"
    port: 389

- name: Install Python LDAP
  ansible.builtin.package:
    name: python3-ldap

- name: Ensure people OU exists
  community.general.ldap_entry:
    dn: ou=People,dc=citc,dc=acrc,dc=bristol,dc=ac,dc=uk
    objectClass:
      - top
      - organizationalUnit
    bind_dn: cn=Directory Manager
    bind_pw: "{{ ldap_dm_password }}"
    server_uri: "ldap://{{ mgmt_hostname }}"
  notify: Restart dirsrv

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
