---
- name: Prepare
  hosts: all
  tasks:
    - name: make ansible facts dir  # Put there by Terraform usually
      file:
        path: /etc/ansible/facts.d
        state: directory
        mode: a=rw,o+x
    - name: create local citc.fact file  # Put there by Terraform usually
      copy:
        content: |
          {"csp":"example", "fileserver_ip":"10.0.0.1", "mgmt_hostname":"mgmt"}
        dest: /etc/ansible/facts.d/citc.fact
        mode: u=rw,g=r,o=r
