---

- name: Wait for packer to finish
  ansible.builtin.async_status:
    jid: "{{ packer_result.ansible_job_id }}"
  register: packer_job_result
  until: packer_job_result.finished
  retries: 200
  delay: 10
  tags: packer

- name: Create directory for the finalised files
  ansible.builtin.file:
    path: /mnt/shared/finalised
    state: directory
    mode: "0755"

- name: Create the finalised file
  ansible.builtin.file:
    path: /mnt/shared/finalised/{{ ansible_hostname }}
    state: touch
    mode: "0777"
