---

- name: Download glauth binary
  get_url:
    url: https://github.com/glauth/glauth/releases/download/v2.2.0/glauth-linux-amd64
    dest: /usr/bin/glauth
    mode: 755

- name: Copy refresh-glauth-config.sh
  copy:
    src: refresh-glauth-config.sh
    dest: /usr/sbin/refresh-glauth-config.sh
    mode: 755

- name: Ensure /etc/glauth dir exists
  file:
    path: /etc/glauth/
    state: directory

- name: Template glauth-preconfig.cfg
  template:
    src: glauth-preconfig.cfg
    dest: /etc/glauth/glauth-preconfig.cfg

- name: Start glauth config refresh script
  ansible.builtin.shell: nohup /usr/sbin/refresh-glauth-config.sh &> /var/log/refresh-glauth-config.log &
  environment:
    WALDUR_URL: "{{ waldur_url | default('https://waldur.example.com/api/') }}"
    WALDUR_TOKEN: "{{ waldur_token }}"
    WALDUR_RESOURCE_UUID: "{{ waldur_resource_uuid }}"
    WALDUR_API_VERIFY_TLS: "{{ waldur_api_verify_tls | default('false') }}"

- name: Start glauth
  ansible.builtin.shell: nohup /usr/bin/glauth -c /etc/glauth/config.cfg &> /var/log/glauth.log &
