---

- name: Download glauth binary
  get_url:
    url: https://github.com/glauth/glauth/releases/download/v2.2.0/glauth-linux-amd64
    dest: /usr/bin/glauth
    mode: 755

- name: Template refresh-glauth-config.sh
  template:
    src: refresh-glauth-config.sh
    dest: /usr/sbin/refresh-glauth-config.sh
    mode: 755

- name: Ensure /etc/glauth dir exists
  file:
    path: /etc/glauth/
    state: directory

- name: Template glauth-preconfig.cfg
  template:
    src: glauth-preconfig.cfg
    dest: /etc/glauth/glauth-preconfig.cfg

- name: Start glauth config refresh script
  ansible.builtin.shell: nohup /usr/sbin/refresh-glauth-config.sh &> /var/log/refresh-glauth-config.log &

- name: Start glauth
  ansible.builtin.shell: nohup /usr/bin/glauth -c /etc/glauth/config.cfg &> /var/log/glauth.log &
