---

- name: Download glauth binary
  get_url:
    url: https://github.com/glauth/glauth/releases/download/v2.2.0/glauth-linux-amd64
    dest: /usr/bin/glauth
    mode: "775"
    force: true

- name: Template refresh-glauth-config.sh
  template:
    src: refresh-glauth-config.sh
    dest: /usr/sbin/refresh-glauth-config.sh
    mode: "775"
    force: true

- name: Ensure /etc/glauth dir exists
  file:
    path: /etc/glauth/
    state: directory

- name: Template glauth-preconfig.cfg
  template:
    src: glauth-preconfig.cfg
    dest: /etc/glauth/glauth-preconfig.cfg

- name: Create service file for the glauth config refresh script
  template:
    src: refresh-glauth-config.service
    dest: /lib/systemd/system/glauth-refresher.service
  notify: Reload systemctl

- name: Start refresh script service
  service:
    name: glauth-refresher.service
    state: started
    enabled: yes

- name: Start glauth
  ansible.builtin.shell: nohup /usr/bin/glauth -c /etc/glauth/config.cfg &> /var/log/glauth.log &
