---
- name: Install OCI tools
  ansible.builtin.pip:
    name:
      - oci
    virtualenv: /opt/cloud_sdk

- name: Create oci config directory
  ansible.builtin.file:
    path: "{{ slurm_elastic.oracle.config_directory }}"
    state: directory
    owner: slurm
    group: slurm
    mode: "0755"

- name: Copy OCI private key
  ansible.builtin.copy:
    src: /home/opc/oci_api_key.pem
    dest: "{{ slurm_elastic.oracle.config_directory }}/oci_api_key.pem"
    owner: slurm
    group: slurm
    mode: "0400"

- name: Configure OCI config file
  ansible.builtin.copy:
    src: /home/opc/config
    dest: "{{ slurm_elastic.oracle.config_directory }}/config"
    owner: slurm
    group: slurm
    mode: "0400"

- name: Install startnode support module
  ansible.builtin.copy:
    src: citc_oci.py
    dest: /opt/cloud_sdk/lib/python3.8/site-packages/citc_cloud.py
    mode: u=rw,g=r,o=r
