---

- name: install sssd
  package:
    name:
      - sssd
      - nss-tools

- name: copy CA cert to trust anchors
  copy:
    src: "{{ ca_cert if ca_cert is defined else '/tmp/CA.crt' }}"
    dest: /etc/pki/ca-trust/source/anchors/389-ds-cert.crt
    remote_src: yes
    mode: preserve

- name: update CA trust anchors
  command: update-ca-trust # noqa no-changed-when

- name: enable SSSD auth in PAM
  command: authselect select sssd --force # noqa no-changed-when

- name: copy sssd config template
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
  notify: restart sssd

- name: start service sssd
  service:
    name: sssd
    state: restarted
    enabled: yes
