---

- name: Install ssh server
  package:
    name: openssh-server

- name: Enable sshd
  service:
    name: sshd
    enabled: true

- name: Set SSHD AddressFamily to inet
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AddressFamily'
    line: "AddressFamily inet"
  notify: Restart sshd
