---

- name: Install ssh server
  ansible.builtin.package:
    name: openssh-server

- name: Enable sshd
  ansible.builtin.service:
    name: sshd
    enabled: true

- name: Set SSHD AddressFamily to inet
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AddressFamily'
    line: "AddressFamily inet"
  notify: Restart sshd
