---

- name: Install ssh server
  ansible.builtin.package:
    name: openssh-server

- name: Enable sshd
  ansible.builtin.service:
    name: sshd
    enabled: true

- name: Set SSHD AddressFamily to inet
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AddressFamily'
    line: "AddressFamily inet"

- name: Add authorized keys feature
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    state: present
    block: |
      AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys
      AuthorizedKeysCommandUser root
  notify: Restart sshd
