---

- name: Configure compute nodes to send syslog
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: '@@remote-host:514'
    line: '*.* @@{{ mgmt_hostname }}:514'
  notify: Restart rsyslog
