---

- name: install rsyslog
  yum:
    name:
      - rsyslog

- name: enable the rsyslog service
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Add InfluxDB repository
  yum_repository:
    name: influxdb
    description: InfluxDB
    baseurl: https://repos.influxdata.com/centos/$releasever/$ansible_architecture/stable/
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: install telegraf package
  package:
    name: telegraf
    state: present
  notify: restart telegraf

- name: enable the telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes

- name: enable network monitoring in telegraf
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[inputs.net]"
    option: interfaces
    value: '["*"]'
    state: present
    mode: u=rw,g=r,o=r
  notify: restart telegraf

- name: configure telegraf to use InfluxDB URL
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[outputs.influxdb]"
    option: urls
    value: '["http://{{ mgmt_hostname }}:8086"]'
    backup: yes
    mode: u=rw,g=r,o=r
  notify: restart telegraf

- include_tasks: "{{ monitoring_role }}.yml"
