---

- name: Install rsyslog
  yum:
    name:
      - rsyslog

- name: Enable the rsyslog service
  service:
    name: rsyslog
    state: started
    enabled: true

# Currently only influxdb is in the aarch64 repo so we must use the arm64 repo. Once they
# are in https://repos.influxdata.com/centos/8/aarch64/stable/ we can change.
- name: Add InfluxDB repository
  yum_repository:
    name: influxdb
    description: InfluxDB
    baseurl: https://repos.influxdata.com/centos/$releasever/{{ "arm64" if ansible_architecture == "aarch64" else ansible_architecture }}/stable/
    gpgcheck: false

- name: Install telegraf package
  package:
    name: telegraf
    state: present
  notify: Restart telegraf

- name: Enable network monitoring in telegraf
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[inputs.net]"
    option: interfaces
    value: '["*"]'
    state: present
    mode: u=rw,g=r,o=r
  notify: Restart telegraf

- name: Configure telegraf to use InfluxDB URL
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[outputs.influxdb]"
    option: urls
    value: '["http://{{ mgmt_hostname }}:8086"]'
    backup: true
    mode: u=rw,g=r,o=r
  notify: Restart telegraf

- name: Enable the telegraf service
  service:
    name: telegraf
    state: started
    enabled: true

- include_tasks: "{{ monitoring_role }}.yml"
