---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    groups:
      - compute
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
  inventory:
    links:
      group_vars: ../../../../group_vars/
verifier:
  name: ansible
