---

- name: Install PyMySQL
  package:
    name: python3-PyMySQL

- name: Install mariadb module
  package:
    name: "@mariadb"

- name: Install mariadb
  yum:
    name:
      - mariadb-server
      - mariadb-devel
    state: installed

- name: Start service mariadb
  service:
    name: mariadb
    state: started
    enabled: true
