---

- name: Install PyMySQL
  ansible.builtin.package:
    name: python3-PyMySQL

- name: Install mariadb module
  ansible.builtin.package:
    name: "@mariadb"

- name: Install mariadb
  ansible.builtin.yum:
    name:
      - mariadb-server
      - mariadb-devel
    state: installed

- name: Start service mariadb
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
