---
- name: Converge
  hosts: all
  tasks:
    - name: Include webui
      include_role:
        name: webui
      vars:
        webui_password_store_directory: /tmp
        ldap_dm_password: this_is_the_ldap_dm_password
