---

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
